# Generated by Django 5.0 on 2023-12-04 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('adoption_status', models.CharField(max_length=100)),
                ('shelter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='monster_api.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(max_length=100)),
                ('application_details', models.CharField(max_length=100)),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='monster_api.pet')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='monster_api.user')),
            ],
        ),
    ]
