# Generated by Django 5.0 on 2023-12-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_api', '0002_pet_model_filename_pet_model_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionapplication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
