# Generated by Django 5.0 on 2023-12-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_api', '0003_alter_adoptionapplication_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
