# Generated by Django 5.0 on 2023-12-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_api', '0004_alter_pet_description_alter_pet_id_alter_shelter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='applicant_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='applicant_adoption_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='applicant_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
